#!/bin/sh
cp /home/ralph/.m2/repository/com/h2database/h2/1.4.192/h2-1.4.192.jar ~/payara41/glassfish/domains/domain1/lib/ext
~/payara41/bin/asadmin create-jdbc-connection-pool --datasourceclassname org.h2.jdbcx.JdbcDataSource --restype javax.sql.DataSource --property url="jdbc\:h2\:mem\:" h2pool
~/payara41/bin/asadmin create-jdbc-resource --connectionpoolid h2pool jdbc/h2